### ISSUE TITLE
웹 소켓 사용 알림 실시간 통신이었지만...

### ISSUE THREAD

**Issue by WooGi1020** [wiki-viki/wiki-viki#107]
# ✨ Feat

## 어떤 작업을 할 예정인가요?

- 자잘한 버그 수정이랑 완성도 있는 페이지를 위해 롤백하고 수정에 집중하겠읍니다 ㅠ

**Comment by miraclee1226** [comment]
헉 대박..😮 홧팅입니다!!ㅎㅎ💪💪
